### ISSUE TITLE
 NoMethodError Exception

### ISSUE THREAD

**Issue by adriannuix** [logstash-plugins/logstash-input-github#14]
I'm trying to use the git plugin but I get:

C:\work\jiras\logstash\ls522>bin/logstash -f gitlogstash3.conf
C:\work\development-environment\Tools\GnuWin32\bin\stty.exe: standard input: Function not implemented
Could not find log4j2 configuration at path /work/jiras/logstash/ls522/config/log4j2.properties. Using default config which logs to console
16:55:24.136 [[main]-pipeline-manager] INFO logstash.pipeline - Starting pipeline {"id"=>"main", "pipeline.workers"=>24, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>3000}
16:55:24.571 [[main]-pipeline-manager] INFO logstash.pipeline - Pipeline main started
16:55:24.650 [Api Webserver] INFO logstash.agent - Successfully started Logstash API endpoint {:port=>9600}

<NoMethodError: undefined method `headers_' for #>
C:/work/jiras/logstash/ls522/vendor/bundle/jruby/1.9/gems/logstash-input-github-3.0.1/lib/logstash/inputs/github.rb:32:in run'
org/jruby/RubyProc.java:281:incall'
C:/work/jiras/logstash/ls522/vendor/bundle/jruby/1.9/gems/ftw-0.0.45/lib/ftw/webserver.rb:77:in handle_request'
C:/work/jiras/logstash/ls522/vendor/bundle/jruby/1.9/gems/ftw-0.0.45/lib/ftw/webserver.rb:59:inhandle_connection'
C:/work/jiras/logstash/ls522/vendor/bundle/jruby/1.9/gems/ftw-0.0.45/lib/ftw/webserver.rb:29:in run'
16:58:31.249 [LogStash::Runner] FATAL logstash.runner - An unexpected error occurred! {:error=>#<NoMethodError: undefined methodheaders_' for #<FTW::Request:0x322b1385>>, :backtrace=>["C:/work/jiras/logstash/ls522/vendor/bundle/jruby/1.9/gems/logstash-input-github-3.0.1/lib/logstash/inputs/github.rb:32:inrun'", "org/jruby/RubyProc.java:281:incall'", "C:/work/jiras/logstash/ls522/vendor/bundle/jruby/1.9/gems/ftw-0.0.45/lib/ftw/webserver.rb:77:inhandle_request'", "C:/work/jiras/logstash/ls522/vendor/bundle/jruby/1.9/gems/ftw-0.0.45/lib/ftw/webserver.rb:59:inhandle_connection'", "C:/work/jiras/logstash/ls522/vendor/bundle/jruby/1.9/gems/ftw-0.0.45/lib/ftw/webserver.rb:29:in`run'"]}
16:58:31.344 [[main]<github] ERROR logstash.pipeline - A plugin had an unrecoverable error. Will restart this plugin.
Plugin: 8083, id=>"04388f32709d653b85caa29a820e09609393f127-1", enable_metric=>true, codec=>"plain_e1b9d3c3-c580-47f0-9663-ea4eb1f21bfa", enable_metric=>true, charset=>"UTF-8">, ip=>"0.0.0.0", drop_invalid=>false>
Error: Bad file descriptor - Bad file descriptor

my config is:
input {
github {
port => 8083
}
}

output {
stdout {
codec => rubydebug
}
}

It's obvious that the plugin get something but it does not seem to be able to parse it. The hook is just listenting for push events at and posts to http://10.10.12.86:8083/

My webhooks are configured properly to handle events and I can see that working when substituting the logstash git plugin with a web server and checking the logs for the webhooks Posts.

Did anybody get this plugin to listen to git hooks?

The C:\work\development-environment\Tools\GnuWin32\bin\stty.exe: standard input: Function not implemented is a not a problem as it appears everywhere with all my working plugins.

Run on Windows as you might have guessed from the path :)

Cheers

**Comment by adriannuix** [comment]
I can also reproduce the same issue with 

curl -H "Content-Type: application/json" -d '{"Something":"xyz","somethingelse":"xyz"}' http://localhost:8083/api/login
curl: (52) Empty reply from server

**Comment by suyograo** [comment]
Fixed in https://github.com/logstash-plugins/logstash-input-github/pull/13

**Comment by suyograo** [comment]
Available in v3.0.2
