### ISSUE TITLE
drop_invalid contains security issue if no header x-hub-signature

### ISSUE THREAD

**Issue by ngapaillard** [logstash-plugins/logstash-input-github#16]
I found a security issue with the plugin. If the header "x-hub-signature" isn't in the request and drop_invalid is setted to "true" then the message isn't dropped...

Version: latest

Operating System: MACOS

Config File :
input {
github {
drop_invalid => true
ip => "0.0.0.0"
port => "8080"
secret_token => "test"
}
}

Steps to Reproduce:
run
curl -XPOST -d'test' localhost:8080
The request won't be dropped by the plugin because the header "x-hub-signature" isn't present, so it pass the control...

**Comment by rsareth** [comment]
Please review it quickly!
